### PR TITLE
WOR-188: added flags for critical and abnormal result ranges

### PR DESCRIPTION
**Pull request by rhenshaw56**

### CODE REVIEW

**Comment by mogoodrich** [comment]
@rhenshaw56 this looks good, though it looks like there are some small merge errors now after I merged in the other pull request.

Also, just wanted to double-check that you confirmed that this works correctly for concepts that don't have high/low normal and high/low critica values defined?

**Comment by rhenshaw56** [comment]
@mogoodrich I have updated the code and fixed the conflicts. For concepts that don't have those ranges defined, I believe it won't show anything, as confirmed from the nutrition form

**Comment by rhenshaw56** [comment]
screen shot 2018-11-27 at 15 07 50

**Comment by mogoodrich** [comment]
Sweet, thanks @rhenshaw56 , merging now!

**Pull request merged**
