### PR TITLE
New Components (OLD PR)

### PR DESCRIPTION
**Pull request by beingtmk**

### CODE REVIEW

**Comment by mogoodrich** [comment]
Thanks @beingtmk ! I will review in the coming days!

**Comment by mogoodrich** [comment]
@beingtmk @JudeNiroshan  sorry, I'm just getting a chance to take a look at this now... first thing, it looks like this PR is somehow reverting changes that have been made since you originally forked the project?  For instance, in the diff, check out ObsHistory.jsx... it looks like this will revert some changes I made on June 7th?  I think you need to pull the latest changes from the master react-components into your branch before submitting the PR?

Thanks!

**Comment by beingtmk** [comment]
@beingtmk, i will fix this!

**Comment by beingtmk** [comment]
@mogoodrich, i have fixed it in a new PR!, #242, you can close this PR!

**Pull request closed without merging**
