### PR TITLE
Order all components imports in index.js

### PR DESCRIPTION
**Pull request by Abdo-A**
I ordered all the components imports in the main entry point of the project (index.js)
The imports are in a more readable for now.

### CODE REVIEW

**Comment by mogoodrich** [comment]
Thanks @Abdo-A  I will take a look in the next couple of days...

**Comment by Abdo-A** [comment]
@jomadoye 
I have addressed your comments.
Thank you.

**Comment by mogoodrich** [comment]
Thanks @Abdo-A  and @jomadoye !

First off, I agree that the index was very disorganized and in need of cleaning up, so thanks for doing this!

And I agree with @jomadoye  that doing ti straight alphabetically, while better than what we currently have, isn't ideal... grouping based on type first makes sense.

We could have further debates on exactly what types to group on, but this is a good start... @jomadoye go ahead and merge this in if you think it looks okay.

And thanks again @Abdo-A !

**Comment by jomadoye** [comment]
Thank you @Abdo-A, this looks neater now. merging it in.

**Pull request merged**
